'use strict';
const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d');
const WORLDS=[{name:'青葱原野',sub:'微风、草地和最初的勇气',sky:'#a9dfcd',far:'#8ac5a2',hill:'#69ae80',ground:'#bba16c',top:'#80ab4c',names:['微风原野','蘑菇小径','森林的守护者']},{name:'落日沙丘',sub:'追随风沙里古老的足迹',sky:'#f0d2a3',far:'#dab481',hill:'#cc9f69',ground:'#ad7953',top:'#e4b86e',names:['金色流沙','遗迹之门','沙漠的回响']},{name:'星夜雪山',sub:'让星光照亮漫长的夜晚',sky:'#a6bacf',far:'#879eb7',hill:'#728ca6',ground:'#879caa',top:'#e1ece4',names:['初雪山谷','极光之桥','云端灯塔']},{name:'熔岩城堡',sub:'为了朋友，向最后的挑战进发',sky:'#55566c',far:'#5e5267',hill:'#493c50',ground:'#705557',top:'#bd7961',names:['余烬之路','城堡深处','最后的星光']}];
const STORIES=[['消失的星光','一个安静的夜晚，守护蘑菇王国的星光突然消失了。远方的城堡传来求救的信号……你，愿意踏上这段旅程吗？','来自桃花公主的一封信'],['蘑菇邮差的约定','蘑菇邮差告诉你：黑影带着星光向沙漠逃去了。先穿过这条小径，帮他找回遗失的星星吧。','邮差：高处也许有惊喜！'],['森林的秘密','古树守护者终于醒来。它说，星光从来没有熄灭，只是等待勇敢的人。收集碎片，打开通向沙漠的路。','守护者：相信你的第二次跳跃。'],['沙中的足迹','热风吹过金色沙丘，一串巨大的脚印通向古老遗迹。旅行商人送来消息：公主就在黑曜石城堡。','旅行商人：别被眼前的沟壑吓倒。'],['遗迹之门','千年前的壁画画着四颗守护星。只有把散落的星光重新聚在一起，王国才会迎来黎明。','壁画上写着：光因分享而明亮。'],['风带来的声音','遗迹深处传来公主的声音：“我还好！去雪山点亮灯塔，它会指引你的方向。”沙暴正在靠近。','桃花公主：我们一定会再见。'],['雪中的朋友','雪山里的小精灵迷了路。你点亮的星光让它找到回家的方向，它也告诉你一条通向山顶的小路。','雪精灵：谢谢你，红帽子的朋友！'],['极光下的桥','穿过悬空的古桥，极光在天空舞动。每一片飘落的雪花，都像是一封来自朋友的祝福。','邮差：大家都在等你回来。'],['点亮云端','灯塔被冰雪覆盖了许多年。带上最后一片雪山星光，让它再次闪耀。远处的熔岩城堡即将显现。','守塔人：勇气就是继续向前。'],['向余烬出发','灯塔的光划破黑暗。城堡就在熔岩河的尽头。一路结识的朋友们，将希望都装进了你的行囊。','朋友们：我们与你同在！'],['门后的真相','你终于发现，魔王偷走星光，是想让自己的城堡不再孤独。可强行留下的光，只会让世界陷入黑暗。','桃花公主：让我们把光带回去。'],['最后的星光','魔王守在终点前。躲开火球，跳到它的头顶三次！用勇气打破阴影，把星光和公主一起带回家。','最终任务：击败魔王，抵达旗帜。']];
let saved={unlocked:0,completed:[],best:{}};try{const s=JSON.parse(localStorage.getItem(window.RewardBridge.storageKey('progress-v1')));if(s&&Number.isInteger(s.unlocked)&&Array.isArray(s.completed))saved={unlocked:Math.max(0,Math.min(11,s.unlocked)),completed:s.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<12),best:s.best||{}}}catch{}
let levelIndex=0,state='ready',level,player,camera=0,keys={},last=0,clock=0,remaining=300,coins=0,stars=0,particles=[],muted=false,toastUntil=0;
const rand=(a,b)=>{const n=Math.sin(a*127.1+b*311.7)*43758.5453;return n-Math.floor(n)};
function sound(f=520,d=.09){if(!muted)window.GameAudio?.effect(f,d)}
function activateAudio(){window.GameAudio?.unlock()}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastUntil=performance.now()+3300}
function rect(x,y,w,h,c,g=ctx){g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),w,h)}
function cloud(g,x,y,s=1,color='#e9f5db'){g.fillStyle=color;[[0,12,66,18],[12,0,23,32],[32,5,23,27],[54,16,18,14]].forEach(r=>g.fillRect(x+r[0]*s,y+r[1]*s,r[2]*s,r[3]*s))}
function hill(g,x,base,w,h,c){g.fillStyle=c;g.beginPath();g.moveTo(x,base);g.lineTo(x,base-h*.22);g.lineTo(x+w*.12,base-h*.22);g.lineTo(x+w*.12,base-h*.5);g.lineTo(x+w*.27,base-h*.5);g.lineTo(x+w*.27,base-h*.77);g.lineTo(x+w*.4,base-h*.77);g.lineTo(x+w*.4,base-h);g.lineTo(x+w*.6,base-h);g.lineTo(x+w*.6,base-h*.77);g.lineTo(x+w*.73,base-h*.77);g.lineTo(x+w*.73,base-h*.5);g.lineTo(x+w*.88,base-h*.5);g.lineTo(x+w*.88,base-h*.22);g.lineTo(x+w,base-h*.22);g.lineTo(x+w,base);g.fill()}
function background(g,w,h,wi,cam=0,preview=false){const t=WORLDS[wi];rect(0,0,w,h,t.sky,g);const scale=h/540;g.save();g.scale(scale,scale);const width=w/scale;if(wi>=2){for(let i=0;i<40;i++){let x=(rand(i,8)*1800-cam*.08)%1800;if(x<0)x+=1800;rect(x,30+rand(i,3)*300,2,2,'#eef0dc',g)}g.fillStyle='#f3eaca';g.beginPath();g.arc(width-140,100,29,0,Math.PI*2);g.fill()}for(let i=-1;i<8;i++){let x=i*260-(cam*.16)%260;cloud(g,x+40,75+rand(i,4)*90,.6+rand(i,7)*.5,wi===3?'#7b7381':wi===2?'#c9d6db':'#edf3d9');hill(g,x-70,465,360,110+rand(i,2)*120,t.far);hill(g,x+80-(cam*.09)%70,480,290,80+rand(i,9)*120,t.hill)}if(preview){rect(0,475,width,65,t.ground,g);rect(0,475,width,12,t.top,g)}g.restore()}
function buildLevel(index){const wi=Math.floor(index/3),stage=index%3,width=3300+stage*500+wi*220,groundY=458;const platforms=[],blocks=[],items=[],enemies=[],pipes=[],gaps=[];for(let i=0;i<3+stage;i++){const x=850+i*650+wi*25;if(x<width-480)gaps.push({x,w:85+stage*12})}let start=0;for(const gap of gaps){platforms.push({x:start,y:groundY,w:gap.x-start,h:110,type:'ground'});start=gap.x+gap.w}platforms.push({x:start,y:groundY,w:width-start,h:110,type:'ground'});
for(let i=0;i<9+stage;i++){let x=320+i*285,y=338-(i%3===1?45:0);if(x>width-340)break;for(let j=0;j<(i%3===0?3:2);j++){let block={x:x+j*38,y,w:36,h:34,type:j===1?'question':'brick',used:false};blocks.push(block);platforms.push(block)}for(let j=0;j<3;j++)items.push({x:x+j*32,y:y-38,w:16,h:22,type:'coin'});if(i%3===2)items.push({x:x+40,y:y-85,w:24,h:24,type:'star'});}
// Exactly three collectible stars in every level.
items.splice(0,0,{x:190,y:405,w:16,h:22,type:'coin'},{x:225,y:405,w:16,h:22,type:'coin'});let existing=items.filter(i=>i.type==='star');while(existing.length>3){items.splice(items.indexOf(existing.pop()),1)}while(existing.length<3){let star={x:width-850+existing.length*160,y:300,w:24,h:24,type:'star'};items.push(star);existing.push(star)}
for(let i=0;i<5+stage+wi;i++){let x=580+i*365;if(x>width-400)break;const ground=platforms.find(p=>p.type==='ground'&&x>=p.x&&x+36<p.x+p.w);if(ground)enemies.push({x,y:426,w:32,h:32,vx:(i%2?1:-1)*(40+wi*9),min:Math.max(ground.x,x-120),max:Math.min(ground.x+ground.w-32,x+150),alive:true})}
for(let i=0;i<3;i++){let x=640+i*1030;if(x>width-350)continue;const ground=platforms.find(p=>p.type==='ground'&&x>=p.x&&x+64<p.x+p.w);if(ground){let p={x,y:394,w:58,h:64,type:'pipe'};pipes.push(p);platforms.push(p)}}
if(index===11)enemies.push({x:width-380,y:388,w:70,h:70,vx:-65,min:width-580,max:width-170,alive:true,boss:true,hp:3,inv:0,fire:2});return {width,platforms,blocks,items,enemies,pipes,wi,flag:width-110,fireballs:[]}}
function loadLevel(index,play=false){if(play&&!window.RewardBridge.canPlay()){window.RewardBridge.requestStart();return;}levelIndex=index;level=buildLevel(index);player={x:90,y:390,w:28,h:38,vx:0,vy:0,ground:false,jumps:0,hp:3,inv:0,face:1};camera=0;remaining=300;coins=0;stars=0;particles=[];keys={};state=play?'playing':'ready';const w=WORLDS[level.wi];$('level-label').textContent=`世界 ${level.wi+1}-${index%3+1}`;$('level-name').textContent=w.names[index%3];$('difficulty').textContent=['初次启程','渐入佳境','勇敢前行','最终挑战'][level.wi];$('chapter').textContent=index===0?'序章':`第 ${index+1} 章`;$('story-title').textContent=STORIES[index][0];$('story-text').textContent=STORIES[index][1];$('story-note').textContent=STORIES[index][2];$('status').textContent=play?'向着星光，继续前进！':'准备好探索新世界了吗？';$('goal-finish').textContent='○';if(play){activateAudio();window.GameAudio?.stopMusic();$('overlay').style.display='none';canvas.focus({preventScroll:true});toast(STORIES[index][2])}else showOverlay('THE STARLIGHT ADVENTURE','每一段冒险<br>都从一小步开始。','星光碎片散落在王国各地。<br>戴好帽子，和马里奥一起找回失落的星光！','开始冒险');updateHUD();renderWorlds()}
function showOverlay(tag,title,text,button){$('overlay').style.display='flex';$('overlay-tag').textContent=tag;$('overlay-title').innerHTML=title;$('overlay-text').innerHTML=text;$('start').innerHTML=button+' <span>→</span>';$('overlay-hint').textContent='按 Enter 键也可以继续'}
function updateHUD(){$('hearts').textContent='♥ '.repeat(Math.max(0,player.hp))+'♡ '.repeat(3-Math.max(0,player.hp));$('coin-count').textContent=String(coins).padStart(3,'0');$('star-count').textContent=`${stars} / 3`;$('timer').textContent=Math.max(0,Math.ceil(remaining));$('goal-coins').textContent=coins>=10?'✓':'○';$('goal-stars').textContent=stars===3?'✓':'○'}
function renderWorlds(){$('progress-count').textContent=`${saved.completed.length} / 12`;$('progress-bar').style.width=`${saved.completed.length/12*100}%`;$('world-grid').replaceChildren();WORLDS.forEach((w,i)=>{const card=document.createElement('article');card.className='world-card'+(level.wi===i?' selected':'');const done=saved.completed.filter(n=>Math.floor(n/3)===i).length;card.innerHTML=`<div class="world-art"><canvas width="580" height="224"></canvas><span class="world-number">WORLD 0${i+1}</span><span class="world-lock">${saved.unlocked>=i*3?'✦ 已解锁':'⌑ 待探索'}</span></div><div class="world-copy"><h3>${w.name}<span>${done} / 3</span></h3><p>${w.sub}</p><div class="level-buttons"></div></div>`;const g=card.querySelector('canvas').getContext('2d');background(g,580,224,i,0,true);if(i===0){drawPipe(g,360,166,42,40);drawMushroom(g,110,171,1.1)}if(i===1){hill(g,330,199,115,107,'#c08d58');hill(g,390,199,125,75,'#d6a56e')}if(i===2){rect(400,125,28,70,'#6c8097',g);rect(394,121,40,10,'#e9ecdb',g);rect(408,136,12,20,'#f3d795',g)}if(i===3){rect(350,135,110,65,'#514251',g);rect(345,111,27,90,'#514251',g);rect(439,111,27,90,'#514251',g);rect(394,163,24,37,'#d5926d',g)}for(let j=0;j<3;j++){const b=document.createElement('button'),n=i*3+j;b.textContent=`${i+1}-${j+1} ${saved.completed.includes(n)?'✓':''}`;b.disabled=n>saved.unlocked;b.title=w.names[j];b.addEventListener('click',()=>{loadLevel(n,true);$('game-screen').scrollIntoView({behavior:'smooth',block:'center'})});card.querySelector('.level-buttons').append(b)}$('world-grid').append(card)})}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:-Math.random()*190,life:.7,color})}
function jump(){if(state!=='playing'||player.jumps>=2)return;player.vy=player.jumps===0?-510:-445;player.jumps++;player.ground=false;sound(player.jumps===1?420:600);burst(player.x+14,player.y+38,'#f5eed0',5)}
function hurt(fall=false){if(player.inv>0&&!fall)return;player.hp--;sound(130,.2);burst(player.x+14,player.y+20,'#e9755e');if(player.hp<=0){state='dead';showOverlay('TAKE A BREATH. TRY AGAIN.','勇气，不止一次。','休息一下，再试一次吧。<br>每一次尝试，都让你离终点更近。','再次挑战');$('status').textContent='冒险还没有结束，再来一次！'}else{player.inv=2;player.vy=-260;if(fall){let p=level.platforms.filter(p=>p.type==='ground'&&p.x<player.x).pop();player.x=Math.min(player.x-110,p.x+p.w-70);player.x=Math.max(p.x+15,player.x);player.y=350;player.vy=0;player.jumps=0}toast('别灰心！还剩 '+player.hp+' 颗生命。')}updateHUD()}
function complete(){state='won';saved.unlocked=Math.max(saved.unlocked,Math.min(11,levelIndex+1));if(!saved.completed.includes(levelIndex))saved.completed.push(levelIndex);saved.best[levelIndex]=Math.max(saved.best[levelIndex]||0,stars);try{localStorage.setItem(window.RewardBridge.storageKey('progress-v1'),JSON.stringify(saved))}catch{toast('浏览器未允许存档，本次进度仍会保留。')}const final=levelIndex===11;showOverlay(final?'THE KINGDOM SHINES AGAIN':'A NEW CHAPTER AWAITS',final?'星光归来，<br>谢谢你，冒险家！':'好样的，冒险家！',final?'公主与朋友们点亮了整个王国。魔王也收到了一颗属于自己的星星。<br>你的勇气，让每个人都拥有了光。':`收集了 ${coins} 枚金币 · ${stars} / 3 颗星光<br>下一站：${WORLDS[Math.floor((levelIndex+1)/3)].names[(levelIndex+1)%3]}`,final?'重新踏上旅程':'前往下一关');$('goal-finish').textContent='✓';$('status').textContent=final?'王国因你而重新闪耀。':'关卡完成，冒险进度已保存。';renderWorlds();sound(780,.3)}
function update(dt){window.GameAudio?.tick(state==='playing',level.wi);clock+=dt;if(state!=='playing')return;remaining-=dt;if(remaining<=0){player.hp=1;hurt();return}player.inv=Math.max(0,player.inv-dt);const dir=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);player.vx=dir*(keys.ShiftLeft||keys.ShiftRight?285:220)*(keys.ArrowDown?.48:1);if(dir)player.face=dir;player.x+=player.vx*dt;player.x=Math.max(0,Math.min(level.width-player.w,player.x));for(const p of level.platforms)if(overlap(player,p)){if(dir>0)player.x=p.x-player.w;else if(dir<0)player.x=p.x+p.w}
const oldY=player.y;player.vy=Math.min(760,player.vy+1320*dt);player.y+=player.vy*dt;player.ground=false;for(const p of level.platforms){if(!overlap(player,p))continue;if(player.vy>=0&&oldY+player.h<=p.y+3){player.y=p.y-player.h;player.vy=0;player.ground=true;player.jumps=0}else if(player.vy<0&&oldY>=p.y+p.h-3){player.y=p.y+p.h;player.vy=70;if(p.type==='question'&&!p.used){p.used=true;coins+=3;burst(p.x+18,p.y,'#f9d965');sound(880);if(level.blocks.indexOf(p)%3===1){level.items.push({x:p.x+5,y:p.y-29,w:25,h:25,type:'mushroom'});toast('发现回复蘑菇！吃掉它恢复生命。')}}}}if(player.y>610){hurt(true);if(state!=='playing')return}
for(const item of level.items){if(item.taken)continue;if(overlap(player,item)){item.taken=true;if(item.type==='coin'){coins++;sound(900,.055)}else if(item.type==='star'){stars++;sound(1200,.18);toast(`找到星光 ${stars} / 3！每一颗都在照亮王国。`)}else{player.hp=Math.min(3,player.hp+1);sound(660,.16);toast('温暖的蘑菇，生命已恢复。')}burst(item.x+10,item.y+10,item.type==='mushroom'?'#ef9373':'#fff0a2')}}
for(const e of level.enemies){if(!e.alive)continue;e.x+=e.vx*dt;if(e.x<e.min||e.x>e.max){e.x=Math.max(e.min,Math.min(e.max,e.x));e.vx*=-1}if(e.boss){e.inv=Math.max(0,(e.inv||0)-dt);e.fire-=dt;if(e.fire<=0){e.fire=2.2;level.fireballs.push({x:e.x,y:e.y+25,w:15,h:15,vx:-185,life:5})}}if(overlap(player,e)){if(player.vy>0&&oldY+player.h<e.y+19){player.vy=-360;player.jumps=1;if(e.boss){if(e.inv<=0){e.hp--;e.inv=.8;burst(e.x+35,e.y,'#e8bf66');toast('魔王的护甲破裂了！剩余 '+e.hp+' 层');if(e.hp<=0){e.alive=false;toast('魔王被击败了！快去旗帜旁迎接公主！');coins+=20}}}else{e.alive=false;coins+=2;burst(e.x+16,e.y+10,'#c7a477')}sound(260)}else hurt()}}
for(const f of level.fireballs){f.x+=f.vx*dt;f.life-=dt;if(f.life>0&&overlap(player,f)){f.life=0;hurt()}}level.fireballs=level.fireballs.filter(f=>f.life>0);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=480*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);camera=Math.max(0,Math.min(level.width-960,player.x-290));if(player.x>level.flag-10){if(level.enemies.some(e=>e.boss&&e.alive)){player.x=level.flag-20;toast('先击败魔王，才能救出公主！')}else complete()}updateHUD()}
function drawPipe(g,x,y,w,h){rect(x+5,y+10,w-10,h-10,'#428a5c',g);rect(x+9,y+10,9,h-10,'#75b674',g);rect(x+w-14,y+10,6,h-10,'#357349',g);rect(x,y,w,14,'#367c50',g);rect(x+3,y+3,w-6,7,'#85bb76',g)}
function drawMushroom(g,x,y,s=1){g.save();g.translate(Math.round(x),Math.round(y));g.scale(s,s);rect(6,13,17,13,'#f7dfb0',g);rect(2,6,25,12,'#d77654',g);rect(7,1,15,8,'#d77654',g);rect(6,7,6,6,'#f7edcf',g);rect(18,5,5,6,'#f7edcf',g);rect(10,19,2,4,'#514b39',g);rect(18,19,2,4,'#514b39',g);g.restore()}
function drawPlayer(){if(player.inv>0&&Math.floor(clock*12)%2===0)return;ctx.save();ctx.translate(Math.round(player.x+14),Math.round(player.y));ctx.scale(player.face,1);const crouch=keys.ArrowDown&&state==='playing';if(crouch){ctx.translate(0,12);ctx.scale(1,.7)}const running=Math.abs(player.vx)>0&&player.ground&&state==='playing',step=running?Math.sin(clock*18)*3:0;rect(-11,0,20,5,'#dc5e43');rect(-14,5,29,5,'#dc5e43');rect(-10,10,20,12,'#f4c695');rect(-11,10,6,10,'#694b33');rect(5,11,3,4,'#374735');rect(8,16,7,5,'#edbd8a');rect(2,19,10,3,'#694b33');rect(-10,23,20,10,'#cc5b42');rect(-6,22,4,12,'#487c89');rect(4,23,4,11,'#487c89');rect(-8,30,17,5,'#487c89');rect(-13,24,5,8,'#f3d8ac');rect(9,24,5,8,'#f3d8ac');rect(-9,34+step,8,5,'#5c5039');rect(3,34-step,9,5,'#5c5039');rect(-4,26,2,2,'#f1d285');rect(5,26,2,2,'#f1d285');ctx.restore()}
function drawStar(x,y,size=13,g=ctx){g.save();g.translate(x,y);g.fillStyle='#fff0a0';g.strokeStyle='#d6a94b';g.lineWidth=2;g.beginPath();for(let i=0;i<10;i++){const r=i%2?size*.45:size,a=-Math.PI/2+i*Math.PI/5;g.lineTo(Math.cos(a)*r,Math.sin(a)*r)}g.closePath();g.fill();g.stroke();rect(-4,-2,2,4,'#9f8639',g);rect(3,-2,2,4,'#9f8639',g);g.restore()}
function draw(){const t=WORLDS[level.wi];background(ctx,960,540,level.wi,camera);ctx.save();ctx.translate(-Math.round(camera),0);for(const p of level.platforms){if(p.x+p.w<camera-50||p.x>camera+1010)continue;if(p.type==='ground'){rect(p.x,p.y,p.w,p.h,t.ground);rect(p.x,p.y,p.w,12,t.top);rect(p.x,p.y+12,p.w,5,level.wi===2?'#bdcfd0':'#7b9254');for(let x=Math.ceil(p.x/28)*28;x<p.x+p.w-5;x+=28){rect(x,p.y+24,5,5,'#ffffff15');rect(x+11,p.y+49,4,4,'#765e3c26')}if(level.wi===0){for(let x=Math.ceil(p.x/135)*135+34;x<p.x+p.w-10;x+=135){rect(x,p.y-8,3,8,'#5e985e');rect(x-4,p.y-5,3,3,'#5e985e');rect(x+6,p.y-4,3,4,'#5e985e')}}}else if(p.type==='pipe')drawPipe(ctx,p.x,p.y,p.w,p.h);else{rect(p.x,p.y,p.w,p.h,p.type==='question'&&!p.used?'#ddb260':'#b89365');rect(p.x+3,p.y+3,p.w-6,2,'#f1d392');rect(p.x,p.y+p.h-3,p.w,3,'#9d7c50');if(p.type==='question'&&!p.used){ctx.fillStyle='#fff3ca';ctx.font='bold 24px monospace';ctx.fillText('?',p.x+11,p.y+25);rect(p.x+4,p.y+5,2,2,'#92733f');rect(p.x+30,p.y+27,2,2,'#92733f')}else if(p.type==='brick'){rect(p.x,p.y+16,p.w,2,'#937c55');rect(p.x+17,p.y,2,16,'#937c55');rect(p.x+8,p.y+18,2,16,'#937c55');rect(p.x+28,p.y+18,2,16,'#937c55')}}}
for(let i=0;i<9;i++){const x=190+i*435;if(x<camera-60||x>camera+1000)continue;if(level.wi===0){hill(ctx,x,458,70,35,'#87b96e');rect(x+32,432,3,6,'#648f59');rect(x+43,432,3,6,'#648f59')}else if(level.wi===1){rect(x,416,12,42,'#889a65');rect(x-10,428,10,8,'#889a65');rect(x-10,417,6,19,'#889a65');rect(x+12,434,10,6,'#889a65');rect(x+18,421,6,19,'#889a65')}}
if(level.wi===3){for(let x=0;x<level.width;x+=30){rect(x,529+Math.sin(clock*3+x)*3,30,12,'#e6975c');rect(x,536,16,4,'#f8cb77')}}
for(const item of level.items){if(item.taken||item.x<camera-30||item.x>camera+990)continue;const y=item.y+Math.sin(clock*3+item.x)*3;if(item.type==='coin'){ctx.fillStyle='#edc35e';ctx.beginPath();ctx.ellipse(item.x+8,y+11,7*Math.abs(Math.cos(clock*2+item.x))+.8,10,0,0,Math.PI*2);ctx.fill();rect(item.x+7,y+5,2,11,'#fff0a5')}else if(item.type==='star')drawStar(item.x+12,y+12);else drawMushroom(ctx,item.x,item.y,.9)}
for(const e of level.enemies){if(!e.alive||e.x<camera-100||e.x>camera+1000)continue;if(e.boss){if(e.inv>0&&Math.floor(clock*10)%2)continue;rect(e.x+8,e.y+16,53,45,'#798553');rect(e.x+5,e.y+29,12,25,'#d4b66b');rect(e.x+47,e.y+27,19,27,'#d4b66b');rect(e.x+17,e.y+4,39,31,'#b69956');rect(e.x+13,e.y,8,12,'#eee3be');rect(e.x+49,e.y,8,12,'#eee3be');rect(e.x+19,e.y+14,8,8,'#fff0cc');rect(e.x+42,e.y+14,8,8,'#fff0cc');rect(e.x+20,e.y+17,4,5,'#574339');rect(e.x+43,e.y+17,4,5,'#574339');rect(e.x+8,e.y+61,22,9,'#7d6045');rect(e.x+43,e.y+61,22,9,'#7d6045');for(let n=0;n<e.hp;n++)rect(e.x+n*24,e.y-16,20,5,'#e19a74')}else{drawMushroom(ctx,e.x,e.y,1.1);rect(e.x+3,e.y+28,11,5,'#6f5940');rect(e.x+21,e.y+28,11,5,'#6f5940');rect(e.x+9,e.y+19,4,3,'#403d2b');rect(e.x+22,e.y+19,4,3,'#403d2b')}}for(const f of level.fireballs){ctx.fillStyle='#f1ba62';ctx.beginPath();ctx.arc(f.x+7,f.y+7,9,0,Math.PI*2);ctx.fill();rect(f.x+9,f.y+3,16,7,'#dc8457')}
rect(level.flag,245,5,213,'#f2e8bb');drawStar(level.flag+2,239,9);rect(level.flag+5,253,51,31,'#478d64');rect(level.flag+5,278,36,9,'#478d64');ctx.fillStyle='#f7e6a0';ctx.font='18px serif';ctx.fillText('✦',level.flag+19,276);rect(level.flag-12,448,30,10,'#a58d61');if(levelIndex===11){rect(level.flag+38,421,20,33,'#ecb3ad');rect(level.flag+41,409,14,15,'#f4d4a0');rect(level.flag+40,404,16,6,'#edcd6d')}
drawPlayer();for(const p of particles)rect(p.x,p.y,4,4,p.color);ctx.restore();if(performance.now()>toastUntil)$('toast').classList.remove('visible')}
function pause(){if(state==='paused'&&!window.RewardBridge.canPlay())return;if(state==='playing'){state='paused';window.GameAudio?.stopMusic();keys={};showOverlay('A LITTLE BREAK','让冒险歇一会儿。','星光会在这里等你。<br>准备好了，就继续向前吧。','继续冒险');$('status').textContent='游戏已暂停'}else if(state==='paused'){activateAudio();state='playing';$('overlay').style.display='none';$('status').textContent='向着星光，继续前进！';canvas.focus({preventScroll:true})}}
function startAction(){if(!window.RewardBridge.canPlay()){window.RewardBridge.requestStart();return;}if(state==='paused')pause();else if(state==='won')loadLevel(levelIndex===11?0:levelIndex+1,true);else loadLevel(levelIndex,true);sound(520)}
$('start').addEventListener('click',startAction);$('pause').addEventListener('click',pause);$('restart').addEventListener('click',()=>loadLevel(levelIndex,true));$('sound').addEventListener('click',()=>{muted=!muted;window.GameAudio?.setEnabled(!muted);$('sound').innerHTML=muted?'♫ <span>声音关</span>':'♪ <span>声音开</span>';$('sound').setAttribute('aria-pressed',String(!muted));sound()});$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('game-screen').requestFullscreen()}catch{toast('当前浏览器暂不支持全屏模式。')}});
document.addEventListener('keydown',e=>{if($('guide').open)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)&&state==='playing')e.preventDefault();if(e.code==='Enter'&&state!=='playing'&&e.target.tagName!=='BUTTON')startAction();if(['KeyP','Escape'].includes(e.code)&&!e.repeat)pause();if(['Space','ArrowUp','KeyW'].includes(e.code)&&!e.repeat)jump();keys[e.code]=true});document.addEventListener('keyup',e=>{keys[e.code]=false});window.addEventListener('blur',()=>{keys={};if(state==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;if(b.dataset.key==='Space')jump()});const release=()=>{keys[b.dataset.key]=false};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release)});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===b));if(b.dataset.view==='worlds')$('worlds').scrollIntoView({behavior:'smooth'});else if(b.dataset.view==='guide'){if(state==='playing')pause();$('guide').showModal()}else $('game-screen').scrollIntoView({behavior:'smooth',block:'center'})}));$('close-guide').onclick=$('guide-ok').onclick=()=>$('guide').close();
loadLevel(saved.unlocked);function frame(now){const dt=Math.min((now-last)/1000||0,.033);last=now;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);

window.RewardBridge.ready({help:()=>{if(state==='playing')pause();$('guide').showModal();},start:startAction,pause:()=>{keys={};if(state==='playing')pause();},mute:(value)=>{muted=value;window.GameAudio?.setEnabled(!value);},destroy:()=>window.GameAudio?.stopMusic()});
