const { chromium, expect } = require(process.env.PLAYWRIGHT_MODULE || '@playwright/test');
const fs = require('fs');
const path = require('path');
const out = path.resolve(__dirname, '../../output/reward-qa'); fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ ...(process.env.REWARD_BROWSER_PATH ? { executablePath: process.env.REWARD_BROWSER_PATH } : { channel: 'chrome' }), headless: true, args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader'] });
  try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.request.post('http://127.0.0.1:8093/api/auth/child/login', { data: { name: '彩蛋体验1', pin: '1234' } });
  await page.goto('http://127.0.0.1:8093/exercise/1');
  await expect(page.locator('.reward-celebration')).toBeAttached();
  await page.waitForTimeout(1750);
  await page.screenshot({ path: `${out}/celebration.png` });
  await expect(page.locator('.reward-celebration')).toHaveCount(0);
  await page.screenshot({ path: `${out}/result.png`, fullPage: true });
  await page.getByRole('link', { name: '现在玩' }).click();
  await expect(page.getByRole('button', { name: '开始游戏', exact: true })).toBeEnabled({ timeout: 20000 });
  await page.screenshot({ path: `${out}/adventure-ready.png`, fullPage: true });
  const before = (await (await page.request.get('http://127.0.0.1:8093/api/easter-eggs/reward')).json()).reward;
  if (before.play) throw new Error('Preparation consumed the reward');
  await page.getByRole('button', { name: '开始游戏', exact: true }).click();
  await expect(page.locator('.reward-start-strip')).toHaveCount(0);
  const adventure = page.frameLocator('iframe');
  await adventure.locator('#game').focus();
  await page.keyboard.down('ArrowRight'); await page.waitForTimeout(650); await page.keyboard.press('Space'); await page.keyboard.up('ArrowRight');
  await page.screenshot({ path: `${out}/adventure-playing.png` });
  const first = (await (await page.request.get('http://127.0.0.1:8093/api/easter-eggs/reward')).json()).reward.play;
  await page.getByRole('button', { name: /卡丁赛车.*选择赛道/ }).click();
  await expect(page.frameLocator('iframe').locator('#game-canvas')).toBeVisible({ timeout: 20000 });
  await page.waitForFunction(() => document.querySelector('iframe')?.contentWindow?.__kart?.snapshot()?.preview === false, null, { timeout: 20000 });
  await page.frameLocator('iframe').locator('#game-canvas').focus();
  await page.waitForFunction(() => document.querySelector('iframe')?.contentWindow?.__kart?.snapshot()?.state === 'racing', null, { timeout: 15000 });
  await page.keyboard.down('ArrowUp'); await page.waitForTimeout(1200); await page.keyboard.up('ArrowUp');
  const kart = await page.locator('iframe').evaluate(el => el.contentWindow.__kart.snapshot());
  if (kart.player.speed <= 0) throw new Error('Racer did not accelerate');
  await page.screenshot({ path: `${out}/racer-playing.png` });
  const switched = (await (await page.request.get('http://127.0.0.1:8093/api/easter-eggs/reward')).json()).reward.play;
  if (switched.expires_at !== first.expires_at) throw new Error('Switch reset the clock');
  await page.getByRole('button', { name: '全屏游戏' }).click();
  await expect(page.locator('.reward-toolbar')).toBeVisible();
  await page.screenshot({ path: `${out}/racer-fullscreen.png` });
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.getByRole('button', { name: '继续游戏', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '继续游戏', exact: true }).click();
  await expect(page.locator('.reward-start-strip')).toHaveCount(0);
  const refreshed = (await (await page.request.get('http://127.0.0.1:8093/api/easter-eggs/reward')).json()).reward.play;
  if (refreshed.expires_at !== first.expires_at) throw new Error('Refresh reset the clock');
  await expect(page.locator('.reward-ended')).toBeVisible({ timeout: 65000 });
  await expect(page.locator('iframe')).toHaveCount(0);
  await page.screenshot({ path: `${out}/ended.png` });
  console.log(JSON.stringify({ checks: 'celebration, preparation, adventure input, racer acceleration, switch, fullscreen, refresh, expiry', first, errors }, null, 2));
  if (errors.length) throw new Error(errors.join('\n'));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
